### ISSUE TITLE
Create Result Issue

### ISSUE THREAD

**Issue by AI35** [adigunsherif/Django-School-Management-System#21]
I got this error when trying to create result

![Capture](https://user-images.githubusercontent.com/24245213/103486433-9a464980-4e06-11eb-9331-74aa2c313adb.JPG)

**Comment by sanjaypradeep** [comment]
thanks for creating the issue.

Hope you have the latest code changes. Unfortunately I cannot able to reproduce this error page on my local. Please share the steps you followed.

**Comment by AI35** [comment]
I got this error on your website https://django-school-app.herokuapp.com/
1 - i opened https://django-school-app.herokuapp.com/result/create/
2 - select first student and clicked on procced button
3 - select English and Physics checkbox
4 - clicked on create button and got this error
