### ISSUE TITLE
FRONTPAGE AND A DATABASE SETUP

### ISSUE THREAD

**Issue by FROST03-cyber** [adigunsherif/Django-School-Management-System#34]
hi guys, so i used this project at my school but the lecturer said it needed a frontend what i mean is at school there is always a backend where the lecturer inputs the marks or data and the frontpage where the students can only see there marks with no access to alter it..so is it possible to add a frontend??? because to me this seems like a backend..kindly get back to me ..i need assistance my due date is almost near

**Comment by adigunsherif** [comment]
Hi, yes it's possible. How soon do you need it and is this a paid service?

**Comment by FROST03-cyber** [comment]
no its just for a school project .but if you can do it how much can you ask for???

**Comment by adigunsherif** [comment]
Please send me a mail at adigunsherif@gmail.com
