### ISSUE TITLE
Data is not visible

### ISSUE THREAD

**Issue by Zakishaikh** [adigunsherif/Django-School-Management-System#43]
** Hey, student data is not visible\displayed after adding the new student manually as well as using CSV file but also able to process those data while making the invoice..**
Kindly Revert as soon as possible..
shaikh.zaki2000@gmail.com

**Comment by AyimNelson** [comment]
apps/students/templates/students/student_detail.html
Student data is not visible [Fixed]
{% for student in students %} -> {% for student in object_list %}

**Comment by adigunsherif** [comment]
Closed with #50
