### ISSUE TITLE
Parent phone number validation required. 

### ISSUE THREAD

**Issue by sanjaypradeep** [adigunsherif/Django-School-Management-System#9]
![image](https://user-images.githubusercontent.com/18122757/88473735-0bbbcb00-cf3e-11ea-9f50-4d2187badb01.png)

Expectation, 
1. should accept only number format. 
2. should accept max of 10 digits (thinking aloud as country as IND)

I'm interested to solve this, please assign to me.

**Comment by adigunsherif** [comment]
Good. Create a pull request and go ahead to solve it, then we can merge it after review. 

Thanks

**Comment by sanjaypradeep** [comment]
PR Raised - https://github.com/adigunsherif/Django-School-Management-System/pull/11/files

Open for discussion.
